<h1>Login</h1>
<?php
    $url = $this->url('application',['controller'=>'Usuario','action'=>'login']);
?>

<form action=<?= $url; ?> method="post">
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" class="form-control">
    </div>

    <div class="form-group">
        <label for="senha">Senha</label>
        <input type="password" id="senha" name="senha" class="form-control">
    </div>

    <div class="form-group">
        <input type="submit" value="Acessar" class="btn btn-primary">
    </div>
</form>