<h1>Entre em contato conosco.</h1>
<form action="\Index\contato" method="post">
    <div class="form-group">
        <label>Nome</label>
        <input type="text" name="nome" class="form-control">
    </div>

    <div class="form-group">
        <label>Email</label>
        <input type="email" name="email" class="form-control">
    </div>

    <div class="form-group">
        <label>Mensagem</label>
        <textarea name="msg" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <input type="submit" value="Enviar email" class="btn btn-primary">
    </div>
</form>